### ISSUE TITLE
NumberWords - Μετατροπή αριθμού ή ποσού σε λέξεις(ολογράφως)

### ISSUE THREAD

**Issue by sonikf** [DoliGreece/DoliGreeceDevs#4]
To module είναι [εδώ δωρεάν](https://www.dolistore.com/en/modules/17-NumberWords.html) αλλά δεν υποστηρίζει τα Ελληνικά. 

Είναι απαραίτητο για να φτιαχτεί και η απόδειξη είσπραξης.

Έφτιαξα το [lang.el_GR.php](https://github.com/DoliGreece/DoliMods/blob/master/htdocs/numberwords/includes/Numbers/Words/lang.el_GR.php) για τα Ελληνικά.

@DoliGreece/core Παρακαλώ για testing και παρατηρήσεις -  βελτιώσεις για να το ανεβάσω και upstream.
Στις δοκιμές μου λειτουργεί ok μέχρι και τα 99999999,99, προσωπικά μου φτάνουν!

Κατεβάστε και εγκαταστήστε το module και απλά προσθέστε στο custom/numberwords/includes/Numbers/ το αρχείο.

![n-w](https://github.com/DoliGreece/DoliGreece/assets/93765174/a1e2740c-b89f-407b-90a2-22a6520903d6)

**Comment by sonikf** [comment]
O κώδικας έγινε δεκτός και από την επόμενη έκδοση του module 5.0.3 θα υποστηρίζει πλέον και τα Ελληνικά.

Μετά τα 99999999,99 υπάρχει γραμματικό πρόβλημα με τις εκατοντάδες.

αντί για
200500600 = Διακόσια Εκατομμύρια Πεντακόσιες Χιλιάδες Εξακόσια

έχουμε
200500600 = **Διακόσιες** Εκατομμύρια Πεντακόσιες Χιλιάδες Εξακόσια

**Comment by rept0id** [comment]
Θα κοιτάξω να το λύσω
